### ISSUE TITLE
psexec replacement?

### ISSUE THREAD

**Issue by yusufozturk** [golang-devops/go-psexec#1]
Sorry for a question as an issue but how do you think go-psexec can be a psexec replacement? The idea of psexec is, transfering a file through SMB and then running it using p/invoke. So you can run commands remotely. But in this case, if I am going to install 'server', then this is simply server/client software. Am I missing something? I didn't test it yet.

Thanks.

**Comment by francoishill** [comment]
Hi @yusufozturk, good question. Back in the day this tool was developed, psexec was unreliable. It would only work sometimes and then timeout and fail other times, on the same machine.

You are right that this tool requires a "server" to be installed, this is no different from psexec though. Although you might not have to install a server for psexec, the server is still running and Windows still has to be "listening" on a tcp port to react on commands.

The thinking behind why we wrote this tool is so that you can install the server with native psexec (or group policies). At least then you only have to rely on native psexec once when you install the server, instead of every time you execute a command. The other reason was that this tool could also become cross platform, since it is written in golang. Native psexec is only Windows.
